apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: urbedigital
spec:
  type: NodePort
  selector:
    app: core-service
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 8094
      targetPort: 8094
